apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: flux-system
spec:
  chart:
    spec:
      chart: cilium
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
      version: "1.19.x"
  interval: 1h
  targetNamespace: kube-system
  values:
    ipam:
      mode: "kubernetes"

    routingMode: "tunnel"
    tunnelProtocol: "vxlan"
    autoDirectNodeRoutes: false
    ipv4NativeRoutingCIDR: "" # Ensure this is empty

    # This manually injects 'tunnel: vxlan' into the ConfigMap
    # which forces the Agent to enable the 'cilium_vxlan' interface.
    extraConfig:
      tunnel: "vxlan"
      enable-ipv4-masquerade: "true"

    # Lower MTU to allow room for VXLAN headers
    mtu: 1400
    # Your physical interface
    devices: "enp1s0"

    # --- L2 & KUBE-PROXY ---
    kubeProxyReplacement: "true"
    l2announcements:
      enabled: true
    socketLB:
      hostNamespaceOnly: false
    k8sServiceHost: 192.168.0.10
    k8sServicePort: 6443

    debug:
      enabled: false
