apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: flux-system
spec:
  chart:
    spec:
      chart: cilium
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
      version: "1.19.x"
  interval: 1h
  targetNamespace: kube-system
  install:
    crds: CreateReplace
  values:
    # Use node PodCIDR (matches kubeadm --pod-network-cidr=10.244.0.0/16)
    ipam:
      mode: kubernetes
    # Replace kube-proxy (eBPF datapath)
    kubeProxyReplacement: true
    # L2 announcements for LoadBalancer IPs (MetalLB replacement)
    l2announcements:
      enabled: true
    # Rate limit for L2 leader election API traffic
    k8sClientRateLimit:
      qps: 25
      burst: 50
