apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: flux-system
spec:
  chart:
    spec:
      chart: cilium
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
      version: "1.19.x"
  interval: 1h
  targetNamespace: kube-system
  values:
    tunnel: vxlan # Forces VXLAN encapsulation
    routingMode: tunnel # Explicitly tells Cilium to use Tunneling (not Native)
    autoDirectNodeRoutes: false # Disables direct routing (required for VXLAN)
    mtu: 1450 # Lowers MTU to fit VXLAN headers (Prevents dropped packets)
    ipv4:
      masquerade: true # Ensures Pods can talk to the internet

    ipam:
      mode: kubernetes
    kubeProxyReplacement: true
    l2announcements:
      enabled: true
    socketLB:
      hostNamespaceOnly: false
    devices: ["enp1s0"]
    k8sClientRateLimit:
      qps: 100
      burst: 200
    k8sServiceHost: 192.168.0.10
    k8sServicePort: 6443
