apiVersion: v1
kind: Service
metadata:
  name: excalidraw
  namespace: excalidraw
  labels:
    app: excalidraw
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      NodePort: 30019
  selector:
    app.kubernetes.io/name: excalidraw
