apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linkding-ts-cert
  namespace: linkding
spec:
  secretName: linkding-tls-secret
  issuerRef:
    name: tailscale-issuer
    kind: ClusterIssuer
  commonName: linkding.tail911e5b.ts.net
  dnsNames:
    - linkding.tail911e5b.ts.net
