apiVersion: v1
kind: Secret
metadata:
    name: operator-oauth
    namespace: tailscale
type: Opaque
stringData:
    client_id: ENC[AES256_GCM,data:+i1t1Dpx5RjgFUoTL7ZcXY0=,iv:+eJodYiJhyu72QlmwaoYt+WS4OW8gocdcOV3FjUr34c=,tag:87KkpAbBbhUZOM7JTTCnyw==,type:str]
    client_secret: ENC[AES256_GCM,data:HaCH3N3tgNXihr7mXCenpOz7+Z8mGm8oVrSu9fGidqoIfayhFPQhw0v9AGRtyXC/xxpOloc33m975z1Nasn4gg==,iv:jn0sQe7kGhFcjMerNozpfELKJrbHz135yLqHr2ttDYM=,tag:hVk9+idj1Zbdlk13yod/QQ==,type:str]
sops:
    age:
        - recipient: age1qw00lw3e249nnrj9yuxr7v6f03x2epn9jfylnmenvskc0mqks9rsq9l003
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBV1VMVzE2OWdWMUxrbmds
            cStWTktpSkFUb1lMSlhCT3ZHRmxiczFkY0g4ClRXWWIvMUk0ZU9ucEFCWWNnT3dT
            Sm1NOGo2RFpKbU1RMW1VUE1xcWswZTQKLS0tIDFaTm5tRTZTbC9Cays1alJLS2Ns
            aFdLZlZpNXQvQTI5Tk5udmhiYWY5WDQK1wYImPLYVNj8xFo4Brleb+UzTcNECpZK
            nsqpVgc4DYIWlA1cYuQzyBLgMlWaD5Z/+SossH7NNOFFEMJeaExDvA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T21:22:46Z"
    mac: ENC[AES256_GCM,data:8dJKetbbhasDkk/sVVjfejMW/+z9CqjkHhrPQqswQNNUveFjm3DuMU5/wpYVQXStBAEe9MFFwwLHrkqv49TEJLJLO1dR+1mdovYTXq/MjMxRgJkaFiBBtVhc22txVO3+pvAlOoeWWZOa59yhV9X9XtUuY/ZzlHUacv8/cJBguLc=,iv:nqiKK47eJlisQHPz0GlWsvTNIXA164bInGy0LTkcuWY=,tag:LLzHJnCwEXE2z3NzOe3gLA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
