apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale-operator
  namespace: tailscale
spec:
  releaseName: tailscale-operator
  chart:
    spec:
      chart: tailscale-operator
      sourceRef:
        kind: HelmRepository
        name: tailscale
        namespace: flux-system
  interval: 1h
  values:
    oauth:
      secretName: operator-oauth
    operatorConfig:
      defaultTags:
        - "tag:k8s-operator"
