apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale-operator
  namespace: tailscale
spec:
  releaseName: tailscale-operator
  chart:
    spec:
      chart: tailscale-operator
      version: "1.90.5"
      sourceRef:
        kind: HelmRepository
        name: tailscale
        namespace: flux-system
  interval: 1h
  values:
    oauth:
      secretName: operator-oauth

    operatorConfig:
      extraArgs:
        - --managed-ca=true
      domain: "tail911e5b.ts.net"
      hostname: "tailscale-operator"
      defaultTags:
        - "tag:k8s-operator"
      # This is how we force the flags since the chart lacks direct fields
      extraEnv:
        - name: OPERATOR_MANAGE_CA
          value: "true"
        - name: OPERATOR_DOMAIN
          value: "tail911e5b.ts.net"
        - name: OPERATOR_HOSTNAME
          value: "tailscale-operator"

    # apiServerProxyConfig is in its own block in the official values
    apiServerProxyConfig:
      mode: "true"

    # Service Account config matches your cluster
    serviceAccount:
      operator:
        name: operator

    installer:
      proxy:
        type: "userspace"

    domain: "tail911e5b.ts.net"
