apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale-operator
  namespace: tailscale
spec:
  releaseName: tailscale-operator
  chart:
    spec:
      chart: tailscale-operator
      sourceRef:
        kind: HelmRepository
        name: tailscale
        namespace: flux-system
  interval: 1h
  values:
    oauth:
      secretName: operator-oauth
    operatorConfig:
      defaultTags:
        - "tag:k8s-operator"
    proxyConfig:
      managedCA: true
    # Ensures the operator has necessary cluster-wide RBAC
    rbac:
      createClusterRole: true
    # This ensures the ServiceAccount name matches what we see in the cluster
    serviceAccount:
      operator:
        name: operator
    # Required to trigger internal TLS/Cert management
    apiServerProxyConfig:
      mode: "true"
    installer:
      proxy:
        type: "userspace"
    domain: "tail911e5b.ts.net"
