apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale-operator
  namespace: tailscale
spec:
  releaseName: tailscale-operator
  chart:
    spec:
      chart: tailscale-operator
      sourceRef:
        kind: HelmRepository
        name: tailscale
        namespace: flux-system
  interval: 1h
  values:
    oauth:
      secretName: operator-oauth

    # 1. Newest Chart version location
    proxyConfig:
      managedCA: true

    # 2. Older Chart version location
    operatorConfig:
      managedCA: true
      defaultTags:
        - "tag:k8s-operator"

    # 3. Direct Environment Override (The "Sure Thing")
    extraEnv:
      - name: OPERATOR_MANAGE_CA
        value: "true"
      - name: OPERATOR_HOSTNAME
        value: "tailscale-operator"

    # Ensure the chart handles its own base RBAC
    rbac:
      create: true
      createClusterRole: true

    serviceAccount:
      operator:
        name: operator

    apiServerProxyConfig:
      mode: "true"

    installer:
      proxy:
        type: "userspace"

    domain: "tail911e5b.ts.net"
