apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitlab
  namespace: gitlab
spec:
  interval: 10m
  chart:
    spec:
      chart: gitlab
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: gitlab-repo
        namespace: gitlab
      interval: 10m
  values:
    replicaCount: 1
    certmanager-issuer:
      email: ""
      enabled: false
