apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mealie
  name: mealie
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mealie
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mealie
    spec:
      containers:
      - image: ghcr.io/mealie-recipes/mealie:latest
        name: mealie
        ports:
          - containerPort: 9000
        volumeMounts:
          - name: mealie-pvc
            mountPath: /var/data
      volumes:
        - name: mealie-pvc
          persistentVolumeClaim: 
            claimName: mealie-pvc
