apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  chart:
    spec:
      chart: metallb
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: flux-system
      version: "0.15.x"
  interval: 1h
  install:
    crds: CreateReplace
  values:
    crds:
      enabled: true
    # L2 mode (default); no BGP/frrk8s
    frrk8s:
      enabled: false
