---
# Windows 10 VirtualMachine 02
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: win10-02
  namespace: vms
  labels:
    app: win10-02
spec:
  runStrategy: RerunOnFailure
  template:
    metadata:
      labels:
        app: win10-02
    spec:
      domain:
        cpu:
          cores: 4
          sockets: 1
          threads: 1
        memory:
          guest: 4Gi
        resources:
          requests:
            memory: 4Gi
        machine:
          type: q35
        firmware:
          bootloader:
            efi:
              secureBoot: false
        features:
          acpi: {}
          apic: {}
          smm:
            enabled: true
          hyperv:
            relaxed:
              enabled: true
            vapic:
              enabled: true
            vpindex:
              enabled: true
            spinlocks:
              enabled: true
              spinlocks: 8191
            synic:
              enabled: true
            synictimer:
              enabled: true
              direct:
                enabled: true
            tlbflush:
              enabled: true
            frequencies:
              enabled: true
            reenlightenment:
              enabled: true
            ipi:
              enabled: true
        clock:
          utc: {}
          timer:
            hpet:
              present: false
            pit:
              tickPolicy: delay
            rtc:
              tickPolicy: catchup
            hyperv: {}
        devices:
          disks:
            - name: bootdisk
              bootOrder: 1
              disk:
                bus: virtio
          interfaces:
            - name: default
              model: virtio
              masquerade: {}
          inputs:
            - type: tablet
              bus: usb
              name: tablet
          rng: {}
      networks:
        - name: default
          pod: {}
      volumes:
        - name: bootdisk
          dataVolume:
            name: win10-02-disk
