apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: |
    title: Homelab Talos Cluster Homepage
    theme: dark
    color: slate
    layout:
      Monitoring:
        header: true
        style: row
        columns: 4
      Apps:
        header: true
        style: row
        columns: 4
    background:
      image: https://cdnb.artstation.com/p/assets/images/images/006/897/659/large/mikael-gustafsson-wallpaper-mikael-gustafsson.jpg
      blur: sm # sm, md, xl... see https://tailwindcss.com/docs/backdrop-blur
      saturate: 100 # 0, 50, 100... see https://tailwindcss.com/docs/backdrop-saturate
      brightness: 50 # 0, 50, 75... see https://tailwindcss.com/docs/backdrop-brightness
      opacity: 100 # 0-100 # providers:
  #   longhorn:
  #     url: https://longhorn.my.network
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Skool Kubecraft:
        - Skool:
            - abbr: sk
              href: https://www.skool.com/kubecraft
    - Personal Blog:
        - Blog:
            - abbr: bl
              href: https://blog.joehomelab.com
              icon: si-devpost-#003E54
    - Socials:
        - Github:
            - abbr: GH
              href: https://github.com/joesabbagh1
              icon: github-light.png
        - Linkedin:
            - abbr: LN
              href: https://www.linkedin.com/in/joe-sabbagh-37912a228/
              icon: linkedin.png
  services.yaml: |
    - Apps:
        # - Wallabag:
        #     href: https://wallabag.alfonsofortunato.net/
        #     description: Wallabag
        #     icon: si-wallabag-#3F6184
        - Linkding:
            href: https://linkding.joehomelab.net/
            description: Linkding
            icon: linkding.png
        - Excalidraw:
            href: https://excalidraw.joehomelab.net/
            description: Excalidraw
            icon: excalidraw-light.png
    - Monitoring:
        - Grafana:
            href: https://grafana.joehomelab.net/
            description: Grafana dashboard
            icon: grafana.png
  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
    - datetime:
        text_size: xl
        format:
          timeStyle: short
    - search:
        provider: google
        target: _blank
  docker.yaml: ""
