apiVersion: v1
kind: Service
metadata:
  name: homepage
  labels:
    app.kubernetes.io/name: homepage
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30055
  selector:
    app.kubernetes.io/name: homepage
