apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkding
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linkding
  strategy:
    type: RollingUpdate
    maxUnavailable: 0
    maxSurge: 1
  template:
    metadata:
      labels:
        app: linkding
    spec:
      securityContext:
        fsGroup: 33
        runAsUser: 33
        runAsGroup: 33

      containers:
        - name: linkding
          image: sissbruecker/linkding:1.31.0
          ports:
            - containerPort: 9090

          securityContext:
            allowPrivilegeEscalation: false

          readinessProbe:
            httpGet:
              path: /
              port: 9090
              initialDelaySeconds: 5
              periodSeconds: 10
              failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /
              port: 9090
              initialDelaySeconds: 5
              periodSeconds: 10
              failureThreshold: 3

          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"

          volumeMounts:
            - name: linkding-data
              mountPath: /etc/linkding/data
      volumes:
        - name: linkding-data
          persistentVolumeClaim:
            claimName: linkding-data-pvc
