apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-data-pvc
  namespace: registry
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: registry-data-pv
  resources:
    requests:
      storage: 50Gi
