apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: commafeed
  name: commafeed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: commafeed
  template:
    metadata:
      labels:
        app: commafeed
    spec:
      containers:
        - image: athou/commafeed:latest-postgresql
          name: commafeed
          ports:
            - containerPort: 8082
          env:
            - name: CF_DATABASE_DRIVERCLASS
              value: "org.postgresql.Driver"
            - name: CF_DATABASE_URL
              value: "jdbc:postgresql://commafeed-db-rw:5432/app"
            - name: CF_DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: commafeed-db-app
                  key: username
            - name: CF_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: commafeed-db-app
                  key: password
